import Link from "next/link";
import { ArrowRight, Boxes, ShieldCheck, Terminal } from "lucide-react";

export default function Home() {
  const proofItems = [
    "diagnose",
    "ux audit",
    "tokens",
    "shadcn export",
    "mcp config",
    "agent install",
  ];

  return (
    <main className="min-h-svh bg-background text-foreground">
      <section className="mx-auto flex w-full max-w-6xl flex-col gap-8 px-6 py-8 sm:px-8 lg:px-10">
        <header className="flex flex-col gap-5 border-b border-border pb-8 md:flex-row md:items-end md:justify-between">
          <div className="max-w-2xl space-y-3">
            <p className="font-mono text-xs uppercase text-muted-foreground">
              design-sandbox
            </p>
            <h1 className="text-3xl font-semibold tracking-normal sm:text-4xl">
              memi 2.4 proof workspace
            </h1>
            <p className="max-w-xl text-sm leading-6 text-muted-foreground">
              A Next.js, Tailwind, and shadcn sandbox where agents run interface-understanding checks before editing UI.
            </p>
          </div>
          <div className="flex flex-wrap gap-2">
            <Link
              href="/labs/shaders"
              className="inline-flex h-10 w-fit items-center gap-2 rounded-md bg-primary px-4 text-sm font-medium text-primary-foreground"
            >
              Open shader lab
              <ArrowRight className="size-4" aria-hidden="true" />
            </Link>
            <Link
              href="/sandbox"
              className="inline-flex h-10 w-fit items-center gap-2 rounded-md border border-border px-4 text-sm font-medium transition-colors hover:bg-accent hover:text-accent-foreground"
            >
              Open sandbox
            </Link>
          </div>
        </header>

        <div className="grid gap-4 lg:grid-cols-[1.1fr_0.9fr]">
          <section className="rounded-md border border-border bg-card p-5 text-card-foreground">
            <div className="mb-5 flex items-center gap-3">
              <span className="flex size-9 items-center justify-center rounded-md bg-secondary text-secondary-foreground">
                <Terminal className="size-4" aria-hidden="true" />
              </span>
              <div>
                <h2 className="text-base font-semibold">Public proof command</h2>
                <p className="text-sm text-muted-foreground">Runs after @memi-design/cli@2.4.0 is published.</p>
              </div>
            </div>
            <pre className="overflow-x-auto rounded-md bg-secondary p-4 text-sm text-secondary-foreground">
              <code>{`pnpm install\npnpm verify`}</code>
            </pre>
          </section>

          <section className="rounded-md border border-border bg-card p-5 text-card-foreground">
            <div className="mb-5 flex items-center gap-3">
              <span className="flex size-9 items-center justify-center rounded-md bg-secondary text-secondary-foreground">
                <ShieldCheck className="size-4" aria-hidden="true" />
              </span>
              <div>
                <h2 className="text-base font-semibold">Gates covered</h2>
                <p className="text-sm text-muted-foreground">No Figma token is required for the default proof.</p>
              </div>
            </div>
            <div className="grid grid-cols-2 gap-2 text-sm">
              {proofItems.map((item) => (
                <span key={item} className="rounded-md border border-border px-3 py-2">
                  {item}
                </span>
              ))}
            </div>
          </section>
        </div>

        <section className="grid gap-4 md:grid-cols-3">
          {[
            ["Design memory", "Source docs, specs, and token context stay in-repo for agents to read before implementation."],
            ["Registry output", "public/r is generated by memi shadcn export and validated by memi shadcn doctor."],
            ["Agent setup", "Agent Skills and MCP config are dry-run checked without writing into a user's machine config."],
          ].map(([title, body]) => (
            <article key={title} className="rounded-md border border-border bg-card p-5">
              <Boxes className="mb-4 size-4 text-muted-foreground" aria-hidden="true" />
              <h2 className="mb-2 text-base font-semibold">{title}</h2>
              <p className="text-sm leading-6 text-muted-foreground">{body}</p>
            </article>
          ))}
        </section>
      </section>
    </main>
  );
}
